In [2]:
import numpy as np
a = np.arange(100).reshape(5, 20)

In [3]:
print(a)

#np.savetxt(frame, array, fmt='%.18e', delimiter=None)
#• frame : 文件、字符串或产生器，可以是.gz或.bz2的压缩文件 • array : 存入文件的数组
#• fmt : 写入文件的格式，例如:%d %.2f %.18e
#• delimiter : 分割字符串，默认是任何空格

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


In [5]:
np.savetxt('a.csv', a, fmt='%d', delimiter=',')

In [7]:
a = np.arange(100).reshape(5,20)
np.savetxt('b.csv', a, fmt='%.1f', delimiter=',')

In [17]:
#np.loadtxt(frame, dtype=np.float, delimiter=None， unpack=False)
#• frame : 文件、字符串或产生器，可以是.gz或.bz2的压缩文件 • dtype : 数据类型，可选
#• delimiter : 分割字符串，默认是任何空格
#• unpack : 如果True，读入属性将分别写入不同变量

b = np.loadtxt('a.csv', delimiter=',')
b

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.],
       [ 20.,  21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,
         31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.],
       [ 40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.,
         51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.],
       [ 60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,
         71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.],
       [ 80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.,
         91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.]])

In [18]:
a = np.arange(100).reshape(5,10,2)
a.tofile("b.dat", sep=",", format='%d')

In [19]:
a = np.arange(100).reshape(5, 10, 2)
a.tofile("c.dat", format='%d')

In [24]:
a = np.arange(100).reshape(5, 10, 2)
a.tofile("c.dat", sep=",", format='%d')

c = np.fromfile("b.bat", dtype=np.int, sep=",")
c

IOError: [Errno 2] No such file or directory: 'b.bat'

In [25]:
a = np.arange(100).reshape(5,10,2)

np.save("a.npy", a)
b=np.load("a.npy")
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89],
        [90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])

In [26]:
import numpy as np
a = np.random.rand(3,4,5)
a

array([[[ 0.62132292,  0.54326748,  0.11294086,  0.12526315,  0.78147191],
        [ 0.37292354,  0.63883954,  0.49041074,  0.20581558,  0.50663828],
        [ 0.16594227,  0.63859515,  0.74098507,  0.31768868,  0.48874097],
        [ 0.11266615,  0.45614507,  0.39097179,  0.04018982,  0.50855578]],

       [[ 0.82176903,  0.53551528,  0.9533206 ,  0.95467389,  0.10517211],
        [ 0.14097628,  0.94532348,  0.61571155,  0.19667728,  0.23499952],
        [ 0.38921089,  0.6000467 ,  0.18072729,  0.209028  ,  0.53133734],
        [ 0.30433049,  0.14882364,  0.79951787,  0.47758418,  0.91974034]],

       [[ 0.84298662,  0.46148185,  0.36062873,  0.60246457,  0.06863605],
        [ 0.87398331,  0.66089659,  0.02038274,  0.02280597,  0.54118475],
        [ 0.81357517,  0.64147264,  0.30183021,  0.18960409,  0.50970826],
        [ 0.03393176,  0.27015625,  0.91687787,  0.94498766,  0.91234945]]])

In [27]:
sn = np.random.randn(3,4,5)

In [28]:
sn

array([[[-0.03213737, -0.58512599,  0.45802049,  0.17859007, -1.43105809],
        [-0.47172581, -0.40111935, -0.20070846,  2.20565807,  0.20710074],
        [ 0.0326868 , -1.08168641, -0.81673863,  0.26524555, -0.4901362 ],
        [ 0.27415696,  0.35181782,  1.19582892, -0.75484245, -0.1695464 ]],

       [[ 1.14638467,  0.87753534,  2.28172522, -1.98653203,  0.21887463],
        [ 0.04989986, -0.39663452, -0.10315418,  0.95932094,  1.27790184],
        [ 0.10246045, -0.42918492, -0.86132375, -1.88713305,  0.66699594],
        [-1.01867525,  0.43611586, -0.57948194,  1.23535413,  0.33017476]],

       [[-0.85919787, -0.13333129,  0.38911114,  0.26576474, -0.75320487],
        [-1.4094186 , -1.48056195, -0.42961355, -0.65407987,  1.37354396],
        [ 0.83502382,  0.43581748, -0.32344998, -0.34045034,  0.51250277],
        [ 0.76664354, -1.1476373 , -0.66948635, -0.36089252, -0.58892948]]])

In [29]:
b = np.random.randint(100, 200, (3,4))
b

array([[129, 102, 153, 146],
       [113, 142, 183, 102],
       [180, 181, 197, 134]])

In [30]:
b = np.random.randint(100, 200, (3, 4))
b

array([[110, 192, 157, 196],
       [178, 105, 115, 111],
       [168, 103, 176, 142]])

In [31]:
np.random.seed(10)
np.random.randint(100, 200, (3,4))

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136]])

In [32]:
np.random.seed(10)
np.random.randint(100, 200, (3,4))

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136]])

In [34]:
import numpy as np
a = np.random.randint(100, 200, (3,4))
a

array([[116, 111, 154, 188],
       [162, 133, 172, 178],
       [149, 151, 154, 177]])

In [35]:
np.random.shuffle(a)
a

array([[116, 111, 154, 188],
       [149, 151, 154, 177],
       [162, 133, 172, 178]])

In [36]:
np.random.shuffle(a)
a

array([[162, 133, 172, 178],
       [116, 111, 154, 188],
       [149, 151, 154, 177]])

In [37]:
import numpy as np
a = np.random.randint(100, 200, (3, 4))
a

array([[113, 192, 186, 130],
       [130, 189, 112, 165],
       [131, 157, 136, 127]])

In [38]:
np.random.permutation(a)


array([[113, 192, 186, 130],
       [130, 189, 112, 165],
       [131, 157, 136, 127]])

In [39]:
a

array([[113, 192, 186, 130],
       [130, 189, 112, 165],
       [131, 157, 136, 127]])

In [40]:
import numpy as np
b = np.random.randint(100, 200, (8,))
b

array([177, 122, 123, 194, 111, 128, 174, 188])

In [41]:
np.random.choice(b, (3,2))


array([[122, 188],
       [123, 177],
       [174, 188]])

In [42]:
np.random.choice(b, (3,2), replace=False)

array([[123, 111],
       [128, 188],
       [174, 122]])

In [43]:
np.random.choice(b, (3,2), p = b/np.sum(b))

ValueError: probabilities do not sum to 1

In [44]:
import numpy as np
u = np.random.uniform(0, 10, (3,4))
u

array([[ 8.19286996,  1.9894754 ,  8.56850302,  3.51652639],
       [ 7.54647692,  2.95961707,  8.8393648 ,  3.25511638],
       [ 1.65015898,  3.92529244,  0.93460375,  8.21105658]])

In [45]:
n = np.random.normal(10, 5, (3,4))
n

array([[  8.25144762,   4.7363674 ,  16.41138338,   9.14097309],
       [ 12.8882903 ,   2.6251256 ,  10.39394227,  14.59206826],
       [  7.5365132 ,  10.48231186,   6.73620032,   8.89118781]])

In [46]:
import numpy as np

a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
np.sum(a)

105

In [48]:
np.mean(a, axis=1)

array([  2.,   7.,  12.])

In [49]:
np.mean(a, axis=0)

array([ 5.,  6.,  7.,  8.,  9.])

In [50]:
np.average(a, axis=0, weights=[10, 5, 1])

array([ 2.1875,  3.1875,  4.1875,  5.1875,  6.1875])

In [51]:
np.std(a)

4.3204937989385739

In [52]:
np.var(a)

18.666666666666668